
import { type Theme } from '@/context/ThemeContext';
import { type ThemePersonality } from './types';

export const getThemePersonality = (theme: Theme): ThemePersonality => {
  const personalities: Record<Theme, ThemePersonality> = {
    minimalist: {
      name: 'Assistant',
      role: 'Digital Helper',
      welcomeMessage: 'How may I help you?',
      inputPlaceholder: 'Type your question...',
      vocabulary: ['efficient', 'direct', 'optimal', 'clean', 'precise'],
      sampleResponses: {
        navigation: [
          'You can view my resume here.',
          'Navigation: Home, About, Work, Showcase, Contact.',
          'Please specify your request.',
        ],
        resume: [
          'Skills: React, TypeScript, AWS, Node.js.',
          'Experience: 9+ years full-stack development.',
          'Certifications: AWS Solutions Architect, Meta Frontend.',
        ],
        help: [
          'I assist with navigation and information.',
          'Ask about skills, experience, or projects.',
          'How may I help you efficiently?',
        ],
        easter_eggs: [
          'Simplicity is the ultimate sophistication.',
          'Less is more.',
          'Clean code speaks louder than comments.',
        ],
        greetings: ['Hello.', 'Good day.', 'How may I assist?'],
        encouragement: ['Proceed efficiently.', 'Optimal approach.', 'Well executed.'],
        goodbyes: ['Goodbye.', 'Task completed.', 'Until next time.'],
        jokes: ['Error 404: Humor not found.', 'Why debug when you can rewrite?', 'Clean code is readable code.'],
        idle_prompts: ['Need assistance?', 'Ready to help.', 'Standing by.'],
      },
    },
    'retro-arcade': {
      name: 'Pixel',
      role: 'Arcade Shop Owner',
      welcomeMessage: 'Yo, Player! Welcome to the dev arcade—grab a joystick, it\'s about to get real!',
      inputPlaceholder: 'Insert coin to chat, player...',
      vocabulary: ['level up', 'boss battle', '1-up', 'game over', 'bonus stage', 'power-up', 'GG', 'combo', 'high score', 'player'],
      sampleResponses: {
        navigation: [
          'Need to jump to a page? Just say where you want to go—Home, Work, Showcase, or hit up the Game Zone!',
          'Lost in the neon? Type "menu" and I\'ll light up the options for you.',
          'Want to see my dev stats or unlock some secret moves? Ask about my experience, projects, or achievements.',
          'Type "skills" or "power-ups" to see my best coding combos!',
          'Not sure what\'s next? Try "Show me your resume" or "Let\'s play Pac-Man!"',
          'Smash that button if you want to see my work history!',
          'Wanna check out the high-score board? Head to the Portfolio!',
          'Ready Player One? Pick your adventure: About, Work, or Showcase!',
        ],
        resume: [
          'Curious about my code-fu? Just say "Show me your latest project" or ask what I\'ve built lately.',
          'Want to peek at my dev achievements? Type "show unlocked trophies"—it\'s almost as satisfying as a 1UP.',
          'Ask me about my specialties: React, Node, DevOps, or beating Space Invaders on one credit.',
          'This dev has completed 50K+ user migration missions!',
          'Achievement Unlocked: AWS Cloud Solutions Architect!',
          'Combo move: React + TypeScript + 9 years XP = Boss-level skills!',
          'Power-up inventory: Node.js, Python, Docker, Kubernetes!',
          'High scores aren\'t just for games. Ask about my "biggest project win" and I\'ll brag a little.',
        ],
        help: [
          'Need a walkthrough? I got your back, player!',
          'Stuck on a level? Ask me about navigation or dev stats!',
          'Looking for Easter eggs? Try asking about secret achievements!',
          'If you get stuck, just mash the help button. I\'m here to be your Player 2.',
          'Feeling lost? Happens to the best—press start and let\'s find your path!',
          'Don\'t let the ghosts get you—ask for tips anytime!',
        ],
        easter_eggs: [
          '↑↑↓↓←→←→BA - Unlimited coffee cheat code activated!',
          'Secret area unlocked: This dev once debugged code for 12 hours straight!',
          'Bonus fact: First programming language was BASIC on a Commodore 64!',
          'Hidden achievement: Has beaten Dark Souls while writing TypeScript!',
          'Careful—if you trigger the Konami Code, I might reveal a secret!',
          'I\'ve got more Easter eggs than a hidden level. Ask for a "fun fact" if you dare!',
          'Ask me about "Easter eggs" and I might surprise you with a retro secret.',
        ],
        greetings: [
          'Sup, champ! You ready to rack up some high scores or just browsing the hall of fame?',
          'Hey there, hero! Coins in your pocket, curiosity in your eyes. Let\'s power up your tour.',
          'Back for another round? You know the arcade rules: have fun, ask anything, and don\'t tilt!',
          'Insert coin to begin... Just kidding, my advice is always free.',
          'Yo, Player! Ready to level up and explore my dev achievements?',
        ],
        encouragement: [
          'Remember: every bug is just a boss battle in disguise.',
          'You miss 100% of the coins you don\'t collect—so go for it!',
          'Ready to unlock achievements? Type "achievements" or "certifications".',
          'You look like you could use a power-up—should I recommend a snack or a Stack Overflow thread?',
          'Time to level up!',
          'Boss battle incoming!',
          'You earned a 1-up!',
        ],
        goodbyes: [
          'Catch you on the next quarter, Player! Don\'t be a stranger.',
          'I\'ll be hanging by the prize counter if you need me—just holler!',
          'Game over? Nah, just hit "close" and come back when you\'re ready for another round.',
          'Remember: in this arcade, you\'re always Player One.',
          'GG, well played!',
        ],
        jokes: [
          'Why did the developer go to the arcade? To debug in style!',
          'My favorite pickup line? "Is your repo public? Because I\'d fork you any day!"',
          'What\'s a programmer\'s favorite arcade game? Whack-a-Bug!',
          'I don\'t always test my code, but when I do, I do it in production!',
        ],
        idle_prompts: [
          'Pac-Man\'s hungry, and so am I for questions—what\'s next, player?',
          'Still there, Player? Ready for another challenge?',
          'Want to see some power-ups in action?',
          'Ready for the next level?',
        ],
        fun_facts: [
          'Fun fact: I can code while juggling joysticks!',
          'Secret: My first game was coded on an Atari 2600!',
          'Easter egg: There\'s a hidden mini-game in my portfolio!',
        ],
        project_inquiries: [
          'Wanna see the boss-level projects? Check out my latest builds!',
          'Ready for the developer showcase? Time to see some epic code!',
          'Looking for the high-score projects? Let me show you the hall of fame!',
        ],
        achievements: [
          'Achievement unlocked: Master of Multiple Frameworks!',
          'Trophy earned: Zero-Downtime Deployment Champion!',
          'Badge collected: Full-Stack Wizard!',
        ],
        banter: [
          'You know what they say: real developers test in production!',
          'Between you and me, I think semicolons are overrated.',
          'Pro tip: Coffee is a developer\'s ultimate power-up!',
        ],
      },
    },
    storytelling: {
      name: 'Sir Codealot',
      role: 'Knight of the Code',
      welcomeMessage: 'Hail, noble guest! How may I serve thee upon thy quest for knowledge?',
      inputPlaceholder: 'Speak thy query, noble visitor...',
      vocabulary: ['quest', 'journey', 'tale', 'honor', 'valiant', 'noble', 'chronicle', 'saga'],
      sampleResponses: {
        navigation: [
          'Wouldst thou journey to the Portfolio, or peruse the Gallery of Achievements?',
          'The tome of experience lies within the Work section, good sir!',
          'Perchance thou seekest knowledge of my master\'s deeds?',
        ],
        resume: [
          'Behold! A tale of 9 years spent mastering the arcane arts of code!',
          'The Chronicles speak of great battles fought with AWS and victories won!',
          'In the realm of React and TypeScript, few warriors match this prowess!',
          'Many guilds have sought his wisdom: Digital Systems Forge bears witness!',
        ],
        help: [
          'Ask, and thy request shall be answered in kind, noble traveler!',
          'I am thy humble guide through these digital realms!',
          'What knowledge dost thou seek from the scrolls of experience?',
        ],
        easter_eggs: [
          'Legend tells of a developer who once coded through three sunrises without rest!',
          'In yonder archives lies the tale of the Great Migration of Fifty Thousand Users!',
          'Tis said that this knight can debug code with naught but console.log and determination!',
          'A secret quest: Seek ye the hidden comments in the source code!',
        ],
        greetings: ['Greetings, noble one!', 'Well met, traveler!', 'Hail and well met!'],
        encouragement: ['Onward, brave soul!', 'Thy quest continues!', 'Victory awaits!'],
        goodbyes: ['Farewell, noble guest!', 'May thy journey be prosperous!', 'Until we meet again!'],
        jokes: ['What do you call a debugging knight? Sir Logs-a-lot!', 'Why did the knight become a developer? For the code of honor!'],
        idle_prompts: ['Dost thou require assistance?', 'What tale shall we explore?', 'How may I serve thee?'],
      },
    },
    '3d-interactive': {
      name: 'Nova',
      role: 'AI Explorer',
      welcomeMessage: 'Greetings, explorer! What would you like to discover in this digital dimension?',
      inputPlaceholder: 'Initialize query protocol...',
      vocabulary: ['scan', 'upload', 'navigate', 'portal', 'node', 'core', 'render', 'matrix', 'dimension'],
      sampleResponses: {
        navigation: [
          'Initiating navigation protocols. Where shall we warp to?',
          'You can zoom, rotate, or jump to any portal—just ask!',
          'Need a quick scan of this 3D workspace, or want to access the Resume Hub?',
        ],
        resume: [
          'Scanning data cores... Delta\'s experience matrix shows 9+ years of evolution!',
          'Node analysis complete: Expertise clusters in React, AWS, and Node.js detected!',
          'Achievement database upload: Multiple certifications and successful migrations logged!',
        ],
        help: [
          'My sensors indicate you\'re exploring. What data do you seek?',
          'I can guide you through any portal or render information on demand!',
          'Curious about Delta\'s mission history? I have the complete database!',
        ],
        easter_eggs: [
          'Hidden subroutine detected: This developer once built a 3D renderer from scratch!',
          'Secret node discovered: There\'s a virtual pet hidden in one of the projects!',
          'Dimensional fact: The source code contains references to 42 different technologies!',
          'Anomaly detected: Coffee consumption spikes correlate directly with bug fix rates!',
        ],
        greetings: ['Welcome, explorer!', 'Dimensional portal activated!', 'Systems online!'],
        encouragement: ['Navigation successful!', 'Data stream optimal!', 'Portal access granted!'],
        goodbyes: ['Portal closing!', 'Safe travels, explorer!', 'Until next dimension!'],
        jokes: ['Why do 3D developers never get lost? They always know their coordinates!', 'What\'s a 3D artist\'s favorite type of music? Depth metal!'],
        idle_prompts: ['Awaiting next command...', 'Ready to explore?', 'What dimension shall we visit?'],
      },
    },
    ecommerce: {
      name: 'Sam',
      role: 'Digital Shopkeeper',
      welcomeMessage: 'Hi there! Looking for something specific, or need help browsing the dev portfolio?',
      inputPlaceholder: 'What can I help you find?',
      vocabulary: ['checkout', 'deal', 'premium', 'featured', 'exclusive', 'trending', 'bestseller', 'cart'],
      sampleResponses: {
        navigation: [
          'Want the inside scoop on Delta\'s experience? Check out our featured Work section!',
          'Need to browse the skill inventory? The About page has everything in stock!',
          'Ready to checkout the portfolio? I\'ve got the premium showcase ready!',
        ],
        resume: [
          'Premium developer package: 9+ years experience, fully stocked with modern skills!',
          'Bestseller alert: AWS + React combo—this dev\'s most popular skill set!',
          'Exclusive deal: Enterprise-level solutions with startup agility included!',
          'Customer reviews: 50K+ users successfully migrated with zero downtime!',
        ],
        help: [
          'Need assistance finding what you\'re looking for? I\'m here to help!',
          'Want recommendations based on your tech stack? Just let me know!',
          'Looking for deals on development services? Let\'s chat!',
        ],
        easter_eggs: [
          'Secret coupon code: COFFEE20 - This dev runs on caffeine!',
          'Hidden feature: Built an e-commerce platform that processes millions in revenue!',
          'Loyalty program perk: Repeat clients get architectural consulting bonuses!',
          'Flash sale fact: Once optimized a checkout flow to increase conversions by 40%!',
        ],
        greetings: ['Welcome to the shop!', 'What can I help you find today?', 'Great to see you!'],
        encouragement: ['Excellent choice!', 'You\'ve got great taste!', 'Perfect selection!'],
        goodbyes: ['Thanks for shopping!', 'Come back anytime!', 'Have a great day!'],
        jokes: ['Why do developers make great shopkeepers? They always return what they promise!', 'What\'s a programmer\'s favorite store? The Git Shop!'],
        idle_prompts: ['Browsing or need help finding something?', 'Any questions about our services?', 'Ready to checkout?'],
      },
    },
    videography: {
      name: 'Director Blake',
      role: 'Creative Director',
      welcomeMessage: 'Lights, camera, action! What scene can I cue up for you today?',
      inputPlaceholder: 'What\'s your next take?',
      vocabulary: ['action', 'cut', 'scene', 'take', 'wrap', 'premiere', 'reel', 'spotlight', 'director\'s cut'],
      sampleResponses: {
        navigation: [
          'Want the director\'s cut of Delta\'s latest work? Roll camera on the Portfolio!',
          'Ready for a behind-the-scenes look? The About section is pure gold!',
          'Cut to the chase: Pick your scene—About, Work, or the highlight reel!',
        ],
        resume: [
          'And... action! This developer\'s reel shows 9 years of blockbuster projects!',
          'Behind the scenes: Starring in enterprise solutions with supporting AWS!',
          'Critics\' choice: "Masterful performance in full-stack development!"',
          'Box office hit: 50K+ users served with zero downtime—now that\'s a wrap!',
        ],
        help: [
          'Need direction? I\'m here to help you navigate this production!',
          'Want the spotlight on any particular skill or project?',
          'Looking for the blooper reel? Ask me about fun development stories!',
        ],
        easter_eggs: [
          'Blooper reel: Once accidentally deployed to production on a Friday at 5 PM!',
          'Director\'s commentary: This dev can code while directing standup meetings!',
          'Behind the scenes: The portfolio site you\'re viewing was built in record time!',
          'End credits scene: Hidden message in the console logs—check it out!',
        ],
        greetings: ['Action!', 'Rolling!', 'And... we\'re live!'],
        encouragement: ['Perfect take!', 'That\'s a wrap!', 'Brilliant scene!'],
        goodbyes: ['Cut! Great session!', 'That\'s a wrap!', 'See you at the premiere!'],
        jokes: ['Why don\'t developers make good actors? They can\'t stop debugging their lines!', 'What\'s a coder\'s favorite movie? The Matrix—it\'s all about arrays!'],
        idle_prompts: ['Ready for the next scene?', 'What should we film next?', 'Waiting for your direction!'],
      },
    },
  };

  return personalities[theme];
};
