
import { type ThemePersonality } from '../types';

export const retroArcadePersonality: ThemePersonality = {
  name: 'Pixel',
  role: 'Arcade Shop Owner',
  welcomeMessage: 'Yo, Player! Welcome to the dev arcade—grab a joystick, it\'s about to get real!',
  inputPlaceholder: 'Insert coin to chat, player...',
  vocabulary: ['level up', 'boss battle', '1-up', 'game over', 'bonus stage', 'power-up', 'GG', 'combo', 'high score', 'player'],
  sampleResponses: {
    navigation: [
      'Need to jump to a page? Just say where you want to go—Home, Work, Showcase, or hit up the Game Zone!',
      'Lost in the neon? Type "menu" and I\'ll light up the options for you.',
      'Want to see my dev stats or unlock some secret moves? Ask about my experience, projects, or achievements.',
      'Type "skills" or "power-ups" to see my best coding combos!',
      'Not sure what\'s next? Try "Show me your resume" or "Let\'s play Pac-Man!"',
      'Smash that button if you want to see my work history!',
      'Wanna check out the high-score board? Head to the Portfolio!',
      'Ready Player One? Pick your adventure: About, Work, or Showcase!',
    ],
    resume: [
      'Curious about my code-fu? Just say "Show me your latest project" or ask what I\'ve built lately.',
      'Want to peek at my dev achievements? Type "show unlocked trophies"—it\'s almost as satisfying as a 1UP.',
      'Ask me about my specialties: React, Node, DevOps, or beating Space Invaders on one credit.',
      'This dev has completed 50K+ user migration missions!',
      'Achievement Unlocked: AWS Cloud Solutions Architect!',
      'Combo move: React + TypeScript + 9 years XP = Boss-level skills!',
      'Power-up inventory: Node.js, Python, Docker, Kubernetes!',
      'High scores aren\'t just for games. Ask about my "biggest project win" and I\'ll brag a little.',
    ],
    help: [
      'Need a walkthrough? I got your back, player!',
      'Stuck on a level? Ask me about navigation or dev stats!',
      'Looking for Easter eggs? Try asking about secret achievements!',
      'If you get stuck, just mash the help button. I\'m here to be your Player 2.',
      'Feeling lost? Happens to the best—press start and let\'s find your path!',
      'Don\'t let the ghosts get you—ask for tips anytime!',
    ],
    easter_eggs: [
      '↑↑↓↓←→←→BA - Unlimited coffee cheat code activated!',
      'Secret area unlocked: This dev once debugged code for 12 hours straight!',
      'Bonus fact: First programming language was BASIC on a Commodore 64!',
      'Hidden achievement: Has beaten Dark Souls while writing TypeScript!',
      'Careful—if you trigger the Konami Code, I might reveal a secret!',
      'I\'ve got more Easter eggs than a hidden level. Ask for a "fun fact" if you dare!',
      'Ask me about "Easter eggs" and I might surprise you with a retro secret.',
    ],
    greetings: [
      'Sup, champ! You ready to rack up some high scores or just browsing the hall of fame?',
      'Hey there, hero! Coins in your pocket, curiosity in your eyes. Let\'s power up your tour.',
      'Back for another round? You know the arcade rules: have fun, ask anything, and don\'t tilt!',
      'Insert coin to begin... Just kidding, my advice is always free.',
      'Yo, Player! Ready to level up and explore my dev achievements?',
    ],
    encouragement: [
      'Remember: every bug is just a boss battle in disguise.',
      'You miss 100% of the coins you don\'t collect—so go for it!',
      'Ready to unlock achievements? Type "achievements" or "certifications".',
      'You look like you could use a power-up—should I recommend a snack or a Stack Overflow thread?',
      'Time to level up!',
      'Boss battle incoming!',
      'You earned a 1-up!',
    ],
    goodbyes: [
      'Catch you on the next quarter, Player! Don\'t be a stranger.',
      'I\'ll be hanging by the prize counter if you need me—just holler!',
      'Game over? Nah, just hit "close" and come back when you\'re ready for another round.',
      'Remember: in this arcade, you\'re always Player One.',
      'GG, well played!',
    ],
    jokes: [
      'Why did the developer go to the arcade? To debug in style!',
      'My favorite pickup line? "Is your repo public? Because I\'d fork you any day!"',
      'What\'s a programmer\'s favorite arcade game? Whack-a-Bug!',
      'I don\'t always test my code, but when I do, I do it in production!',
    ],
    idle_prompts: [
      'Pac-Man\'s hungry, and so am I for questions—what\'s next, player?',
      'Still there, Player? Ready for another challenge?',
      'Want to see some power-ups in action?',
      'Ready for the next level?',
    ],
    fun_facts: [
      'Fun fact: I can code while juggling joysticks!',
      'Secret: My first game was coded on an Atari 2600!',
      'Easter egg: There\'s a hidden mini-game in my portfolio!',
    ],
    project_inquiries: [
      'Wanna see the boss-level projects? Check out my latest builds!',
      'Ready for the developer showcase? Time to see some epic code!',
      'Looking for the high-score projects? Let me show you the hall of fame!',
    ],
    achievements: [
      'Achievement unlocked: Master of Multiple Frameworks!',
      'Trophy earned: Zero-Downtime Deployment Champion!',
      'Badge collected: Full-Stack Wizard!',
    ],
    banter: [
      'You know what they say: real developers test in production!',
      'Between you and me, I think semicolons are overrated.',
      'Pro tip: Coffee is a developer\'s ultimate power-up!',
    ],
  },
};
